web:
  build: . # Where to look for the Dockerfile to build from
  ports:
    - "4444:3443"
  volumes:
    - ./app:/usr/src/app # This is mounted to the host, aka synced to your computer, to support hot-loading
    - /usr/src/app/node_modules # This is a "data volume" (see docker docs) to store our node_modules
  links:
    - pg
  environment:
    - PGHOST=pg
    - PGDATABASE=postgres
    - PGUSER=postgres
pg:
  image: postgres
