nginx:
  build: ./nginx
  links:
    - node:node
  ports:
    - "80:80"
    - "443:443"
node:
  build: .
  ports:
    - "8080:8080"
  volumes:
    - ./app:/usr/src/app
    - /usr/src/app/node_modules
  links:
    - pg
  environment:
    - PGHOST=pg
    - PGDATABASE=postgres
    - PGUSER=postgres
pg:
  build: ./postgres
  ports:
    - "5432:5432"
